### PR TITLE
feat(backend): list certificates

### PR DESCRIPTION
**Pull request by emjunior258**
Implement the `listIssuedCerts` API operation.

### CODE REVIEW

**Review by snhane — APPROVED** [review]

**Comment by snhane** [comment]
unit tests coming soon, right?

**Comment by emjunior258** [comment]
Don't bother about unit tests @snhane . We will fight for coverage once the features are implemented.

**Comment by emjunior258** [comment]
> unit tests coming soon, right?

My idea is that we do unit tests after we implement the features. A huge debt, I know, but that's the plan

**Comment by snhane** [comment]
It's for my own benefit. 
Cos I couldn't understand what's failing before

**Pull request merged**
