### PR TITLE
chore: setup unit testing for backend

### PR DESCRIPTION
**Pull request by snhane**
Please review

### CODE REVIEW

**Comment by emjunior258** [comment]
Code coverage report is not setup. I can't see code coverage in sonarcloud

**Comment by snhane** [comment]
Got it. 
Will address it

**Comment by emjunior258** [comment]
Maybe also rename the title to `chore: setup unit testing for backend`

**Comment by snhane** [comment]
> Code coverage report is not setup. I can't see code coverage in sonarcloud

The pic below, is what we're looking for, right?
image

**Comment by emjunior258** [comment]
Yes @snhane that's what's expected

**Pull request merged**
